apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo.fullname" . }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.odoo.adminPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo.fullname" . }}-db
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.odoo.database.password | b64enc | quote }}
