# kubernetes/overlays/stage/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: odoo-stage

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml

configMapGenerator:
- name: odoo-config
  behavior: merge
  literals:
  - list_db=False
  - workers=3
  - max_cron_threads=2
  - log_level=info

replicas:
- name: odoo
  count: 2

commonLabels:
  environment: stage
  managed-by: gitlab-ci